INSERT INTO category (id, name) VALUES (1, 'Вышивка бисером');
INSERT INTO category (id, name) VALUES (2, 'Вышивка крестом');
INSERT INTO category (id, name) VALUES (3, 'Алмазная мозаика');
INSERT INTO category (id, name) VALUES (4, 'Вышивка лентами');
INSERT INTO product (id, name, price, description, category_id) VALUES (1, 'Chrysanthemums', 2169, 'Набор для вышивания бисером Абрис Арт "Хризантемы", 31 х 38 см', 1);
INSERT INTO product (id, name, price, description, category_id) VALUES (2, 'AngelInWinter', 806, 'Набор для вышивания бисером Волшебное Мгновение "Ангелочек зимой", 29 х 28 см', 1);
INSERT INTO product (id, name, price, description, category_id) VALUES (3, 'ChinesePeonies', 2459, 'Набор для вышивания бисером Абрис Арт "Китайские пионы", 31 х 38 см', 1);
INSERT INTO product (id, name, price, description, category_id) VALUES (4, 'MorningAtTheMill', 1115, 'Набор для вышивания бисером Ажур "Утро на мельнице", 30 х 40 см', 1);
INSERT INTO product (id, name, price, description, category_id) VALUES (5, 'SummerMorning', 1059, 'Набор для вышивания крестом Чудесная игла "Летнее утро", 40 х 30 см', 2);
INSERT INTO product (id, name, price, description, category_id) VALUES (6, 'WinterWreath', 1119, 'Набор для вышивания крестом Panna "Зимний венок", 28 x 30 см', 2);
INSERT INTO product (id, name, price, description, category_id) VALUES (7, 'MorningOnTheCoast', 1479, 'Набор для вышивания крестом Алиса "Утро на побережье", 38 х 31см', 2);
INSERT INTO product (id, name, price, description, category_id) VALUES (8, 'ItalianYard', 639, 'Набор для вышивания крестом "Итальянский дворик", 42 см х 32 см', 2);
INSERT INTO product (id, name, price, description, category_id) VALUES (9, 'MagicTime', 1669, 'Картина стразами Алмазная Живопись "Магия времени" (АЖ-1558), 38 цветов, 40х40 см', 3);
INSERT INTO product (id, name, price, description, category_id) VALUES (10, 'RosesAndHydrangeas', 1329, 'Картина стразами Алмазная Живопись "Розы и гортензии" (АЖ-1508), 46 цветов, 30х40 см', 3);
INSERT INTO product (id, name, price, description, category_id) VALUES (11, 'MorningDaisies', 1499, 'Картина стразами Алмазная Живопись "Утренние ромашки" (АЖ-1511), 30 цветов, 40х40 см', 3);
INSERT INTO product (id, name, price, description, category_id) VALUES (12, 'MountainWaterfall', 1341, 'Картина стразами Алмазная Живопись "Горный водопад" (АЖ-1347), 26 цветов, 30х40 см', 3);
INSERT INTO product (id, name, price, description, category_id) VALUES (13, 'SmallBouquet', 849, 'Набор для вышивания лентами Цветной "Маленький букет", 20 х 30 см', 4);
INSERT INTO product (id, name, price, description, category_id) VALUES (14, 'SummerColors', 979, 'Набор для вышивания лентами Цветной "Краски лета", 20 х 30 см', 4);
INSERT INTO product (id, name, price, description, category_id) VALUES (15, 'ChamomileAndLavender', 979, 'Набор для вышивания лентами Цветной "Ромашки и лаванда", 20 х 30 см', 4);
INSERT INTO product (id, name, price, description, category_id) VALUES (16, 'Blackberry', 979, 'Набор для вышивания лентами Цветной "Ежевика", 20 х 30 см', 4);
